import { NewsItem } from "./models/newsItem";

export const NEWS: NewsItem[] = [
    {"id": 1, "title": "Очень важная новость 1", "imgUrl": "https://placehold.jp/3d4070/ffffff/500x281.png", "tag": "business", "published": "8 hours ago", "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla magna nunc, scelerisque non dolor ut, scelerisque pellentesque diam. Cras id enim tempor, ornare quam et, tempus mauris. Nunc quis sem mauris. Nam eu purus ut erat varius posuere. Nunc posuere ullamcorper ligula, congue pharetra tellus cursus at. Praesent aliquet mi a turpis molestie, sed egestas ipsum sodales. Suspendisse in nulla tortor. Phasellus fringilla orci vitae pulvinar accumsan. Proin auctor, dolor sed luctus eleifend, nisi justo bibendum dui, vitae molestie orci lorem id dui. Cras ut nulla id massa pellentesque suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra."},
    {"id": 2, "title": "Как Галкин развлекает олигархов: уберите детей от экранов", "imgUrl": "https://placehold.jp/3d4070/ffffff/500x281.png", "tag": "event", "published": "6 hours ago", "text": "Обслуживал богатых: подноготную доходов Галкина в России раскрыли. Максим Галкин получал свои миллионы не на телевидении. Российский репортер Георгий Иващенко рассекретил информацию о доходах Максима Галкина, который вместе со своей семьей уехал из России. По его словам, основной заработок юмориста был совсем не от федеральных каналов, где Галкин успешно вел популярные телешоу, и не от концертов. Иващенко уверен, что свои миллионы супруг Аллы Пугачевой заработал на приватных корпоративах. Поклонники Максима переживают, что артист может остаться без работы, даже если вернется на родину. В интервью порталу BLITZ+ Иващенко рассказал, что без денег Галкин точно сидеть не будет. 'Я уверен, что корпоративов у Максима Галкина будет огромное количество. Думаю, что для бизнесменов не составит труда пригласить его в Прибалтику, например, или куда угодно. Работы у Максима будет огромное количество, особенно на закрытых мероприятиях', - заявил он. Недавно в сети появилась информация о том, что Максим снова начал выступать - правда, пока не в России. Концерты артиста запланированы как в Прибалтике, так и в более дальних странах, например, Англии и Ирландии"},
    {"id": 3, "title": "Очень важная новость 3", "imgUrl": "https://placehold.jp/3d4070/ffffff/500x281.png", "tag": "business", "published": "14 hours ago", "text": "news_text_3"},
    {"id": 4, "title": "Очень важная новость 4", "imgUrl": "https://placehold.jp/3d4070/ffffff/500x281.png", "tag": "business", "published": "23 hours ago", "text": "news_text_4"},
    {"id": 5, "title": "Очень важная новость 5", "imgUrl": "https://placehold.jp/3d4070/ffffff/500x281.png", "tag": "event", "published": "2 hours ago", "text": "news_text_5"},
    {"id": 6, "title": "Очень важная новость 6", "imgUrl": "https://placehold.jp/3d4070/ffffff/500x281.png", "tag": "business", "published": "1 hours ago", "text": "news_text_6"},
    {"id": 7, "title": "Очень важная новость 7", "imgUrl": "https://placehold.jp/3d4070/ffffff/500x281.png", "tag": "health", "published": "20 hours ago", "text": "news_text_7"}
]